/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer, utils} from "ethers";
import type {Provider} from "@ethersproject/providers";
import type {
  ExtraCalldataEOASignaturesValidator,
  ExtraCalldataEOASignaturesValidatorInterface,
} from "../../../../contracts/solidity-utils/helpers/ExtraCalldataEOASignaturesValidator";

const _abi = [
  {
    inputs: [],
    name: "getDomainSeparator",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getNextNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ExtraCalldataEOASignaturesValidator__factory {
  static readonly abi = _abi;
  static createInterface(): ExtraCalldataEOASignaturesValidatorInterface {
    return new utils.Interface(
      _abi
    ) as ExtraCalldataEOASignaturesValidatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExtraCalldataEOASignaturesValidator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExtraCalldataEOASignaturesValidator;
  }
}
