/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type {IAuthorizerAdaptor} from "./IAuthorizerAdaptor";
export type {IAuthorizerAdaptorEntrypoint} from "./IAuthorizerAdaptorEntrypoint";
