/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer, utils} from "ethers";
import type {Provider} from "@ethersproject/providers";
import type {
  IPoolVersion,
  IPoolVersionInterface,
} from "../../../../../@balancer-labs/v2-interfaces/contracts/pool-utils/IPoolVersion";

const _abi = [
  {
    inputs: [],
    name: "getPoolVersion",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolVersion__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolVersionInterface {
    return new utils.Interface(_abi) as IPoolVersionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolVersion {
    return new Contract(address, _abi, signerOrProvider) as IPoolVersion;
  }
}
